export const goodsArray = [
    {
      id: 1,
      img: "https://dull-rose-pawpaw.glitch.me/img/38.jpg",
      title: "Strauß aus Tulpen Dolche Vita (51 Stk)",
      dateDelivery: "heute um 14:00 Uhr",
      price: "670",
    },
    {
      id: 2,
      img: "https://dull-rose-pawpaw.glitch.me/img/39.jpg",
      title: "Strauß aus Rosen Grand Avalanche (101 Stk)",
      dateDelivery: "heute um 14:00 Uhr",
      price: "1480",
    },
    {
      id: 3,
      img: "https://dull-rose-pawpaw.glitch.me/img/40.jpg",
      title: "Strauß aus Rosen Grand Vanilla Cream (101 Stk)",
      dateDelivery: "heute um 14:00 Uhr",
      price: "1980",
    },
    {
      id: 4,
      img: "https://dull-rose-pawpaw.glitch.me/img/41.jpg",
      title: "Strauß aus Rosen Grand Mirabel (101 Stk)",
      dateDelivery: "heute um 14:00 Uhr",
      price: "2130",
    },
    {
      id: 5,
      img: "https://dull-rose-pawpaw.glitch.me/img/42.jpg",
      title: "Strauß mit 101 ecuadorianischen Rosen Mix",
      dateDelivery: "heute um 14:00 Uhr",
      price: "1420",
    },
    {
      id: 6,
      img: "https://dull-rose-pawpaw.glitch.me/img/43.jpg",
      title: "Strauß Mona Lisa (Delphinium)",
      dateDelivery: "heute um 14:00 Uhr",
      price: "1360",
    },
    {
      id: 7,
      img: "https://dull-rose-pawpaw.glitch.me/img/1.jpg",
      title: "Autorisches Bouquet aus Rosen, Dianthus und Trockenblumen",
      dateDelivery: "heute um 14:00 Uhr",
      price: "300",
    },
    {
      id: 8,
      img: "https://dull-rose-pawpaw.glitch.me/img/2.jpg",
      title: "Autorisches Bouquet aus Rosen, Gerbera, Dianthus und Trockenblumen",
      dateDelivery: "heute um 14:00 Uhr",
      price: "200",
    },
    {
      id: 9,
      img: "https://dull-rose-pawpaw.glitch.me/img/3.jpg",
      title: "Autorisches Bouquet aus Rosen und Trockenblumen",
      dateDelivery: "heute um 14:00 Uhr",
      price: "220",
    },
    {
      id: 10,
      img: "https://dull-rose-pawpaw.glitch.me/img/4.jpg",
      title: "Monostrauß aus Tulpen",
      dateDelivery: "heute um 14:00 Uhr",
      price: "160",
    },
    {
      id: 11,
      img: "https://dull-rose-pawpaw.glitch.me/img/5.jpg",
      title: "Autorisches Bouquet aus Rosen und Dianthus",
      dateDelivery: "heute um 14:00 Uhr",
      price: "270",
    },
    {
      id: 12,
      img: "https://dull-rose-pawpaw.glitch.me/img/6.jpg",
      title: "Monostrauß aus Trockenblumen",
      dateDelivery: "heute um 14:00 Uhr",
      price: "150",
    },
    {
      id: 13,
      img: "https://dull-rose-pawpaw.glitch.me/img/7.jpg",
      title: "Blumen in einer Box mit Lilien und Orchideen",
      dateDelivery: "heute um 14:00 Uhr",
      price: "340",
    },
    {
      id: 14,
      img: "https://dull-rose-pawpaw.glitch.me/img/8.jpg",
      title: "Autorisches Bouquet aus Lilien und Chrysanthemen",
      dateDelivery: "heute um 14:00 Uhr",
      price: "290",
    },
    {
      id: 15,
      img: "https://dull-rose-pawpaw.glitch.me/img/9.jpg",
      title: "Monostrauß aus Pfingstrosen",
      dateDelivery: "heute um 14:00 Uhr",
      price: "250",
    },
    {
      id: 16,
      img: "https://dull-rose-pawpaw.glitch.me/img/10.jpg",
      title: "Blumen in einem Korb mit bunten Ranunkeln",
      dateDelivery: "heute um 14:00 Uhr",
      price: "380",
    },
    {
      id: 17,
      img: "https://dull-rose-pawpaw.glitch.me/img/11.jpg",
      title: "Strauß aus Trockenblumen und Lavendel",
      dateDelivery: "heute um 14:00 Uhr",
      price: "170",
    },
    {
      id: 18,
      img: "https://dull-rose-pawpaw.glitch.me/img/12.jpg",
      title: "Blumen in einer Box aus Gerbera und Iris",
      dateDelivery: "heute um 14:00 Uhr",
      price: "320",
    },
    {
      id: 19,
      img: "https://dull-rose-pawpaw.glitch.me/img/13.jpg",
      title: "Blumen in einem Korb mit Frühlingsblumen-Mix",
      dateDelivery: "heute um 14:00 Uhr",
      price: "360",
    },
    {
      id: 20,
      img: "https://dull-rose-pawpaw.glitch.me/img/14.jpg",
      title: "Monostrauß aus Gänseblümchen",
      dateDelivery: "heute um 14:00 Uhr",
      price: "140",
    },
    {
      id: 21,
      img: "https://dull-rose-pawpaw.glitch.me/img/15.jpg",
      title: "Autorisches Bouquet aus Gladiolen und Alstroemerien",
      dateDelivery: "heute um 14:00 Uhr",
      price: "310",
    },
    {
      id: 22,
      img: "https://dull-rose-pawpaw.glitch.me/img/16.jpg",
      title: "Strauß aus Trockenblumen mit Eukalyptus",
      dateDelivery: "heute um 14:00 Uhr",
      price: "200",
    },
    {
      id: 23,
      img: "https://dull-rose-pawpaw.glitch.me/img/17.jpg",
      title: "Blumen in einer Box mit Sukkulenten und Calla",
      dateDelivery: "heute um 14:00 Uhr",
      price: "370",
    },
  ];